services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: rsv
    ports:
      - "5432:5432"  # Expose PostgreSQL on default port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data
    networks:
      - app-network

  springboot-app:
    build: .
    container_name: BOOKING-MS
    depends_on:
      - postgres  # Ensure the postgres container is ready before Spring Boot starts
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rsv
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Password
    ports:
      - "8081:8081"  # Expose the Spring Boot app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
